### ISSUE TITLE
Example in the docs?

### ISSUE THREAD

**Issue by chmac** [ImmoweltGroup/jest-react-redux#4]
Would be great to see an example of how this can package can be used.

Looks like a very helpful package, thanks for sharing, would be awesome to see some introductory docs to get folks started.

**Comment by Inkdpixels** [comment]
Hey @chmac - Thanks for your feedback, have you seen https://immoweltgroup.gitbooks.io/jest-react-redux/docs/api/createMapStateToPropsSnapshot.html already? If that is the case, is there anything we could do to improve the docs? :)

**Comment by Inkdpixels** [comment]
Closed since no feedback was provided, if there is anything we can do to enhance the docs let us know @chmac! :)

**Comment by chmac** [comment]
@Inkdpixels Aha, don't think I saw that docs link. Nice, that's definitely a useful example. Maybe change the Documentation links on the README.md to point to that doc site instead of the repo readme files?
